" Auto-install vim-plug if not present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugin management with vim-plug
call plug#begin('~/.vim/plugged')

" Molokai colorscheme
Plug 'tomasr/molokai'

" Airline/powerline
Plug 'vim-airline/vim-airline'
Plug 'Lokaltog/powerline-fonts'
Plug 'vim-airline/vim-airline-themes'

" Ctrl-P
Plug 'kien/ctrlp.vim'

" supertab
Plug 'ervandew/supertab'

" Auto-pairs
Plug 'jiangmiao/auto-pairs'

" Comments handling
Plug 'tomtom/tcomment_vim'

" Match-it
Plug 'vim-scripts/matchit.zip'

" Surround
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'

" Select blocks
Plug 'michaeljsmith/vim-indent-object'

" Blockit
Plug 'sk1418/blockit'

" Select regions
Plug 'terryma/vim-expand-region'

" ack-grep
Plug 'mileszs/ack.vim'

" ag
Plug 'rking/ag.vim'

" Show number of results
Plug 'henrik/vim-indexed-search'

" Show marks
Plug 'kshenoy/vim-signature'

" gundo
if version >= 703
  Plug 'sjl/gundo.vim'
endif

" netrw
Plug 'vim-scripts/netrw.vim'

" vinegar
Plug 'tpope/vim-vinegar'

" tasklist
Plug 'vim-scripts/TaskList.vim'

" Git support
Plug 'tpope/vim-fugitive'

" Show differences from git repository
if version >= 703
  Plug 'airblade/vim-gitgutter'
endif

" Syntax checking
Plug 'scrooloose/syntastic'

" Create tags automatically
Plug 'xolox/vim-misc'

" Show ctags tagbar
Plug 'majutsushi/tagbar'

" Autocomplete C/C++ code
Plug 'Rip-Rip/clang_complete'

" Autocomplete for Python
if has('python') || has('python3')
  Plug 'davidhalter/jedi-vim'
endif

" PEP8 for Python
if has('python') || has('python3')
  Plug 'nvie/vim-flake8'
endif

" Sets up node.js configuration
Plug 'moll/vim-node'

" Improve JSON highlighting
Plug 'elzr/vim-json'

" Plugins for handling puppet files
Plug 'rodjek/vim-puppet'
Plug 'godlygeek/tabular'

" Navigate tmux and vim panes seamlessly
Plug 'christoomey/vim-tmux-navigator'

" Trace syntax highlighting groups
Plug 'gerw/vim-HiLinkTrace'

" WakaTime
if has('python') || has('python3')
  Plug 'wakatime/vim-wakatime'
endif

" Python coverage module
Plug 'alfredodeza/coveragepy.vim'

" Alda music composer syntax
Plug 'daveyarwood/vim-alda'

call plug#end()

" Enable filetype detection and plugins
filetype plugin indent on

" Enable syntax highlighting
syntax on

" Enable UTF-8 encoding
set encoding=utf-8

" Set viminfo to store sessions
set viminfo+=!

" Autoread external changes
set autoread

" gundo configuration

if version >= 703
  set undodir=~/.vim/tmp/undo/
  set undofile
  set history=256
  set undolevels=256
endif

" Don't save temporary files in current directory
set backupdir=~/.vim/tmp/backup/
set directory=~/.vim/tmp/swap/

" Show line numbers
set number

" Show relative line numbers
if version >= 704
  set relativenumber
endif

" Show ruler
set ruler

" Define scroll offset
set scrolloff=2

" Tabs configuration
set showtabline=2

" Set minimum window height
set winminheight=0

" Allow command completion
set wildmenu
set wildmode=list:full

" Don't show invisible characters by default
set nolist

" Disable mouse support (conflicts with tmux)
set mouse=
" set ttymouse=xterm2

" Backspace can delete indent, eol and line start
set backspace=indent,eol,start

" Define wrap line text
set nowrap

" Allow breaking lines
set linebreak

" Show break
set showbreak=…

" Number of spaces for tabs
set tabstop=2

" Number of spaces for each step of autoindent
set shiftwidth=2

" Highlight maximum recommended width
if version >= 703
  set colorcolumn=79
endif

" Set indentation for specific file types
autocmd FileType python setlocal shiftwidth=4 tabstop=4
autocmd FileType sh setlocal shiftwidth=4 tabstop=4
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType vim setlocal shiftwidth=2 tabstop=2

" Round indent to multiples of shiftwidth
set shiftround

" Expand tabs to spaces
set expandtab

" Copy indentation of current line when starting a new line
set autoindent

" Do smart autoindenting
set smartindent

" Enable highlighting search results
set hlsearch

" Enable progressive search results
set incsearch

" Ignore case in search patterns
set ignorecase

" Use smart case pattern matching
set smartcase

" Search for tags file recursively in parent directories
set tags=./tags

" Avoid delays when pressing ESC
set timeoutlen=1000 ttimeoutlen=0

" Remap leader key
let mapleader = "\<space>"

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %

""" COLORS AND LOOK'N'FEEL
" Set colorscheme
set t_Co=256
set background=dark
let g:molokai_original = 1
let g:rehash256 = 1
try
  colorscheme molokai
catch /^Vim\%((\a\+)\)\=:E185/
  " deal with it
endtry

" Set config for airline/powerline
set laststatus=2
let g:airline_powerline_fonts   = 1
let g:airline_theme             = 'molokai'
let g:airline_enable_branch     = 1
let g:airline_enable_syntastic  = 1
let g:airline#extensions#tabline#enabled = 1

if &term =~ '^screen'
  " tmux will send xterm-style keys when its xterm-keys option is on
  execute 'set <xUp>=\e[1;*A'
  execute 'set <xDown>=\e[1;*B'
  execute 'set <xRight>=\e[1;*C'
  execute 'set <xLeft>=\e[1;*D'
endif

" Trigger configuration. Do not use <tab> if you use
" https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsListSnippets="<s-tab>"
let g:UltiSnipsJumpForwardTrigger="<c-f>"
let g:UltiSnipsJumpBackwardTrigger="<c-b>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" Set supertab to navigate from top to bottom
let g:SuperTabDefaultCompletionType = '<c-n>'
let g:SuperTabContextDefaultCompletionType = '<c-n>'

" Prevent autocompletion after several characters
let g:SuperTabNoCompleteAfter = ['^', ',', ':', "'", '"', ')', '\s']

" Avoid popping up after dot
let g:jedi#popup_on_dot = 0

" Avoid selecting the first item in the completion menu by default
let g:jedi#popup_select_first = 0

" Avoid opening up the preview window
autocmd FileType python setlocal completeopt-=preview

""" HIGHLIGHTING
" Highlight all words like the one under the cursor
" Adapted from http://stackoverflow.com/questions/15999958/can-an-autocmd-be-turned-on-off
let g:toggleHighlight = 0
function! ToggleHighlight(...)
  if a:0 == 1 " Toggle behaviour
    let g:toggleHighlight = 1 - g:toggleHighlight
  endif

  if g:toggleHighlight == 0 " Normal action, highlight
    silent! exe printf('2match IncSearch /\V\<%s\>/', escape(expand('<cword>'), '/\'))
  else
    " Clear the matches
    silent! exe printf('2match IncSearch //', escape(expand('<cword>'), '/\'))
  endif
endfunction

autocmd WinEnter,CursorMoved * call ToggleHighlight()
autocmd WinLeave * 2match IncSearch //

" Start with automatic highlighting of current word disabled
call ToggleHighlight(1)

" Highlight trailing whitespaces
highlight Error ctermbg=red ctermfg=white guibg=red guifg=white
autocmd ColorScheme * highlight Error ctermbg=red ctermfg=white guibg=red guifg=white
match Error '\s\+$'
autocmd WinEnter,BufWinEnter * match Error /\s\+$/
autocmd InsertEnter * match Error /\s\+\%#\@<!$/
autocmd InsertLeave * match Error /\s\+$/
autocmd WinLeave,BufWinLeave * match Error //

" Remove trailing whitespaces
function! RemoveTrailingWhitespaces()
  :%s/  *$//gc
endfunction

" Disable concealing in JSON highlighter
let g:vim_json_syntax_conceal = 0

" Set cursorline (only for the active window)
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END

""" SOME TWEAKS FOR IMPROVING PERFORMANCE
""" extracted from https://eduncan911.com/software/fix-slow-scrolling-in-vim-and-neovim.html
" Set lazyredraw
set lazyredraw

" Disable syntax highlighting after 128 columns and set minlines to 256
set synmaxcol=128
syntax sync minlines=256

" Better highlighting of matching brackets and parenthesis
highlight MatchParen cterm=none ctermbg=250 ctermfg=235
"highlight MatchParen cterm=none ctermbg=250 ctermfg=235 gui=none guibg=250 guifg=235

""" NAVIGATION
" Open and source vimrc easily
nnoremap <leader>c :e ~/git/dotfiles/vim/vimrc<CR>
nnoremap <leader>s :source ~/git/dotfiles/vim/vimrc<CR>

" Jump to the end of the text just pasted
vnoremap <silent> y y`]
vnoremap <silent> p p`]
nnoremap <silent> p p`]

" Allow indent multiple times
vnoremap < <gv
vnoremap > >gv

" Select increasing regions with v
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" <CR> highlights all occurences of the current word without moving
noremap <CR> :let @/='\<<C-R>=expand("<cword>")<CR>\>'<CR>:set hls<CR>

" Press Space to turn off highlighting and clear any message already displayed.
nnoremap <silent> <Space><Space> :nohlsearch<Bar>:echo<CR>

" Easier split windows navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Navigate split windows and maximize them with Alt-<Up> and Alt-<Down>
nmap <silent> <A-Up> :wincmd k<CR>:wincmd _<CR>
nmap <silent> <A-Down> :wincmd j<CR>:wincmd _<CR>

" Switch buffers
map <S-Tab> :bnext<CR>

" Shortcut for Ag
nnoremap <leader>a :Ag!

" Rope shortcuts
if has('python')
  map <leader>rd :RopeGotoDefinition<CR>
  map <leader>rr :RopeRename<CR>
  map <leader>rev :RopeExtractVariable<CR>
  map <leader>rem :RopeExtractMethod<CR>
endif

" Pycoverage shortcuts
nnoremap <leader>pc :PyCoverageHighlight<CR>
nnoremap <leader>pC :PyCoverageClear<CR>

" shortcuts for git
nnoremap <leader>gd :Gvdiffsplit<CR>
nnoremap <leader>gD :diffoff!<CR><c-w>o<CR> " switch back to current file and closes fugitive buffer
nnoremap <leader>gb :Git blame<CR>
nnoremap <leader>gs :Git status<CR>
nnoremap <leader>gc :Git commit<CR>
nnoremap <leader>gp :Git push<CR>
nnoremap <leader>gw :!git add . && git commit -m 'WIP' && git push<CR>

" gitgutter shortcuts
nnoremap <leader>hn :GitGutterNextHunk<CR>
nnoremap <leader>hp :GitGutterPrevHunk<CR>

" Make quickfix window always at the bottom and 5 rows height
function! SetQuickfixWindow()
  wincmd J
  5wincmd _
endfunction
autocmd FileType qf call SetQuickfixWindow()

" Toggle readonly mode (useful when diff'ing)
nnoremap <leader>ro :set readonly!<CR>

" associate *.sapc with custom sapc filetype
au BufRead,BufNewFile *.sapc set filetype=sapc
au BufRead,BufNewFile *.sapc set syntax=json

""" REMAP some F-keys
" F2: Toggle paste mode to avoid screwing indentation
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

" F3: Toggle gundo
nnoremap <F3> :GundoToggle<CR>

" F4: Toggle show invisible characters
map <F4> :set invlist<CR>

" F6: Toggle tasklist
map <F6> :TaskList<CR>

" F8: Toggle Tagbar
nmap <F8> :TagbarToggle<CR>
" Make sure that the tagbar is opened for supported files
"autocmd FileType * nested :call tagbar#autoopen(0)

" F9: Toggle highlighting all matches of current word
map <F9> :call ToggleHighlight(1)<CR>

""" MISC
" PEP8 configuration
let g:flake8_max_line_length=120
let g:flake8_ignore='W391'        " Blank line at end of file

" Call flake8 when saving python files
"autocmd BufWritePost *.py call Flake8()

